### ISSUE TITLE
Would it be possible to implement for &[T; N] ?

### ISSUE THREAD

**Issue by j-hc** [est31/serde-big-array#15]
Like this:
```rust
#[derive(Serialize, Deserialize)]
pub struct Arr<'a, const N: usize> {
    #[serde(with = "BigArray")]
    arr: &'a [&'a str; N], // or maybe [&'a str; N] ?
}
```

**Comment by est31** [comment]
How should the deserializer allocate the data?

**Comment by j-hc** [comment]
im not sure to be honest. like how it does for &'a str ?

this is what im doing right now, it is not very convenient to pass around Cows but i guess handling this exact case is out of the scope of your crate

```rust
#[derive(Serialize, Deserialize)]
pub struct Arr<'a, const N: usize> {
    #[serde(with = "serde_big_array::BigArray")]
    arr: [Cow<'a, str>; N]
}
```

**Comment by est31** [comment]
> like how it does for &'a str but N times ?

Interesting, didn't know that serde supported that, although I'm still not entirely sure how it works...

**Comment by j-hc** [comment]
i just needed to explicitly mark the field as `borrow`. it works now thanks!
#[derive(Serialize, Deserialize)]
pub struct Arr<'a, const N: usize> {
    #[serde(with = "serde_big_array::BigArray", borrow)]
    arr: [&'a str; N]
}
