### ISSUE TITLE
Support for Option<large array> ?

### ISSUE THREAD

**Issue by TomzBench** [est31/serde-big-array#18]
I have a type with a large Optional array.  I get the error:
 `the trait "BigArray<'_>" is not implemented for "std::option::Option<[u8; 4096]>"`

I think there is a way I could probably use the BigArray type with a custom serializer/deserializer but im not exactly sure how. Also, it might be of interest if this Option<array> was implemented as part of this crate?  Because I would not likely be able to impl BigArray for my Option<[u8; 4096]> unless I use a wrapper type which i would rather just use custom ser/de then

**Comment by est31** [comment]
Related to #7

**Comment by est31** [comment]
This should now work with the new `Array` struct.
