### ISSUE TITLE
Is it possible to remove the constraint T: Copy?

### ISSUE THREAD

**Issue by Boscop** [est31/serde-big-array#6]
Is it possible to remove the constraint `T: Copy`?

I tried switching all my old code to using this crate. I had been using this macro, which doesn't require `T: Copy` (but it uses `mem::uninitialized()` so I want to switch to this crate):
```rust

use serde::{Serialize, Serializer};

pub fn serialize_array<S, T>(array: &[T], serializer: S) -> Result<S::Ok, S::Error>
where
	S: Serializer,
	T: Serialize,
{
	array.serialize(serializer)
}

#[macro_export]
macro_rules! serde_array {
	($m:ident, $n:expr) => {
		pub mod $m {
			use super::*;
			use serde::{de, Deserialize, Deserializer};
			use std::{mem, ptr};
			pub use $crate::serialize_array as serialize;

			pub fn deserialize<'de, D, T>(deserializer: D) -> Result<[T; $n], D::Error>
			where
				D: Deserializer<'de>,
				T: Deserialize<'de> + 'de,
			{
				let slice: Vec<T> = Deserialize::deserialize(deserializer)?;
				if slice.len() != $n {
					return Err(de::Error::custom("input slice has wrong length"));
				}
				unsafe {
					let mut result: [T; $n] = mem::uninitialized();
					for (src, dst) in slice.into_iter().zip(&mut result[..]) {
						ptr::write(dst, src);
					}
					Ok(result)
				}
			}
		}
	};
}

serde_array!(a64, 64);
serde_array!(a120, 120);
serde_array!(a128, 128);
serde_array!(a384, 384);
```

But some of my struct members where I used this macro consist of an array with a T that's not Copy. So I can't switch those to this crate :/

Would it be possible to remove this constraint from this crate's macro?

**Comment by est31** [comment]
First, your code is unsound if it contains any pointers or has any custom drop logic (which types that are not Copy usually do). Also, `mem::uninitialized` is deprecated on latest Rust. We should use `MaybeUninit`, which has only been stabilized recently and is not available on the MSRV compiler of one of the reverse dependencies of serde-big-array (`average` crate).

So I think we can't add Copy support per default, at least for now.

I'd be okay with an optional feature for `Copy` support though that uses `MaybeUninit`.

**Comment by Boscop** [comment]
@est31 I meant what I need is support for non-`Copy` types :) 
`[T; N]` where `T` is not `Copy` (but `Clone`). Would it be possible to support it in a sound way in `serde-big-array`?

**Comment by est31** [comment]
I've removed the Copy and Default constraints from the `const-generics` feature (as it requires an MSRV beyond the addition of MaybeUninit): ad8ee0ae8dae33cfa55deccb5620e070008b627d

In later versions of the library, maybe semver breaking ones, I want to remove the `big_array` macro and make that `const-generics` feature the default.
