### ISSUE TITLE
Support for nested arrays?

### ISSUE THREAD

**Issue by Boscop** [est31/serde-big-array#7]
How can it be used with nested arrays without having to introduce a newtype?
E.g. `[[bool; 128]; 2]` or `[[bool; 128]; 128]`.
> the trait bound `[[bool; 128]; 2]: BigArray<'_>` is not satisfied

---

Could this crate be extended with a custom syntax to be able to specify on which nesting level(s) to use `BigArray` for serialization?
E.g. 
```rust
#[serde(with = "[BigArray]")] // means: use BigArray for 2nd dimension
foo: [[bool; 128]; 2]

#[serde(with = "BigArray[BigArray]")] // means: use BigArray for 1st and 2nd dimension
bar: [[bool; 128]; 128]

#[serde(with = "BigArray[[BigArray]]")] // means: use BigArray for 1st and 3rd dimension
baz: [[[bool; 128]; 2]; 128]

#[serde(with = "(BigArray, [BigArray], BigArray[BigArray])")] // also works for tuples
boz: ([bool; 128], [[bool; 128]; 2], [[bool; 128]; 128])
```

I think it would be very useful, and the nesting syntax mirrors the array/tuple syntax :)

**Comment by est31** [comment]
That's an easy one. One only has to implement BigArray... at least I think. Working on a patch.

**Comment by est31** [comment]
Not as easy as I thought. The `BigArray` trait is implemented for arrays `[T; N]` for `N` from the specified set and `T: Default + Copy + Serialize + Deserialize`. With the exception of `Copy`, those traits are only implemented for arrays with size < 32. Extending the `with` syntax is not possible from this crate, for that `serde_derive` has to be changed. Also it seems to me that the API of serde is structured in a way that it doesn't allow a deeper level of nesting, as `BigArray` needs Serialize and Deserialize to be implemented for `T`. Thus, I doubt there is something we can do here :/.

**Comment by est31** [comment]
@Boscop do you have any current code that you want to replace? I'm interested in how it works.

**Comment by Boscop** [comment]
@est31 I don't have any macro solution for this yew, but I think it's possible by introducing a new trait that means "can be serialized as element of a big array" (e.g. `BigArrayItem`) and there would be a blank impl for all `T: Sized + Default + Copy + $crate::reex::Serialize + $crate::reex::Deserialize<'de>` and also for `T: $name` (`$name` aka `BigArray`).
And then changing this 
https://github.com/est31/serde-big-array/blob/29b38f1deec66b07d1fc10b266169ba694e1de5f/src/lib.rs#L125
to `pub trait $name<'de>: BigArrayItem<'de> {` 
(so any `BigArray` is also a `BigArrayItem`)
and this
https://github.com/est31/serde-big-array/blob/29b38f1deec66b07d1fc10b266169ba694e1de5f/src/lib.rs#L133
to `where T: BigArrayItem<'de>`.
This should allow any nesting level because `BigArrayItem` will be impl'd for all types that are currently possible as items (all `T: Default + Copy + $crate::reex::Serialize + $crate::reex::Deserialize<'de>`) **and** for big arrays as well.

**Comment by est31** [comment]
> (so any BigArray is also a BigArrayItem)

I'm not sure this will work. `BigArrayItem` requires `Serialize + Deserialize` but `BigArray` doesn't implement those for the same reason that this very crate exists :p.

**Comment by Boscop** [comment]
@est31 Then you can add the `Serialize + Deserialize` bound only to the `where` clause of the `impl $name`. Then it should work, I think!

**Comment by pietervandermeer** [comment]
Would love to see this feature, but a workaround is ok as well. Am I right in saying that wrapping a nested array in a box will work?

**Comment by Vixeliz** [comment]
Would this also allow just normal boxed arrays? I don't seem to be able to make a boxed large array

**Comment by est31** [comment]
@Vixeliz I think that's a different thing but not 100% sure. In the meantime, you could try using `Box<[u8]>` as a workaround.

This might actually be a good idea, it might make sense for this crate to define newtypes for arrays... hmmm....

**Comment by Vixeliz** [comment]
I ended up working around it by making a strict that contains an array with the serde with big array. Then use that in the box instead of an array directly a little annoying but works

**Comment by Vixeliz** [comment]
But yeah the same thing could be done in crate and just make sure to implement Index and IndexMut as another option.

**Comment by est31** [comment]
I've done this in 8d2c9ad8486b805f216e1cf9af2447c3660bb2c2 . One can now use the `Array` struct:

```Rust
#[derive(Serialize, Deserialize)]
struct S {
    arr: Array<Array<u8, 234>, 65>,
}
```

It is less convenient than the `BigArray` trait but it supports nesting. If anyone has any ideas how to improve it, please suggest them!

**Comment by Vixeliz** [comment]
@est31 I think implementing index and indexmut might be helpful

**Comment by est31** [comment]
@Vixeliz yes that was a subsequent commit. I also want to impl `Deref` and `DerefMut`, and maybe more traits.

**Comment by Vixeliz** [comment]
Ah kk thanks for adding it so quickly!

**Comment by Vixeliz** [comment]
@est31 out of curiosity when will a new release be released?

**Comment by est31** [comment]
@Vixeliz Feedback would be very welcome. Would it be possible that you try out the `Array` struct in your code and tell me if you like it? Then if you do like it, I could do the release. You can [include serde-big-array from git](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) for your experiment.

**Comment by Vixeliz** [comment]
@est31 At least in my project it was as easy as just replacing any instances where I needed the serialized array. One exception which wasn't a problem for me since I was already using a custom type before is ofc any functions such as .len need to be array.0.len which there isnt really anything you can do about minus deref which would be *array.len. So personally since its not like its gonna automatically replace peoples arrays it seems good enough for me at first glance.

**Comment by est31** [comment]
> any functions such as .len need to be array.0.len

[`.len()` should work](https://github.com/est31/serde-big-array/blob/c82df1fd8b58956dd398caec0952ed57291ef5cf/tests/nested.rs#L19), thanks to the `Deref` trait being implemented. Same trick as the one I did for `Arc`.

Your feedback sounds positive, thanks for trying it out. I will make a release soon-ish.

**Comment by Vixeliz** [comment]
Yes that’s what I meant I forgot star is only if you’re not calling functions.

**Comment by Vixeliz** [comment]
Didn’t realize that you implemented deref already so no complaints here. Thanks for the quick turnaround!
