### ISSUE TITLE
error: cannot find attribute serde in this scope

### ISSUE THREAD

**Issue by tpmccallum** [est31/serde-big-array#8]
Hi
I am trying to use serde big array in a situation where serde is an optional feature. Here is the code ...

```
use serde_big_array::big_array;
#[cfg(feature = "serde")]
use serde_crate::{Deserialize, Serialize};
```
```
big_array! {
    BigArray;
    60,
}
#[derive(Clone, Copy)]
#[cfg_attr(
    feature = "serde",
    derive(Serialize, Deserialize),
    serde(crate = "serde_crate")
)]
struct SixtyBytes {
    #[serde(with = "BigArray")]
    arr: [u8; Monty480::ENCODED_SIZE_BYTES],
}
```
I am receiving the following error when I run this type of implementation ...
```
error: cannot find attribute `serde` in this scope
--> src/api_480.rs:935:7
935 |     #[serde(with = "BigArray")]
                  ^^^^^
error: aborting due to previous error
```
The actual code, that produces the error, can be found [here](https://github.com/tpmccallum/recrypt-rs/blob/optional_serde_feature/src/api_480.rs#L924).

The [Cargo.toml file](https://github.com/tpmccallum/recrypt-rs/blob/optional_serde_feature/Cargo.toml) is set up like this ...
```
[dependencies]
serde-big-array = "0.2.0"

[dependencies.serde_crate]
package = "serde"
optional = true
version = "1.0.89"
default-features = false
features = ["std", "derive"]

[features]
serde = ["serde_crate"]
```
Any ideas would be greatly appreciated.

Kind regards
Tim

**Comment by est31** [comment]
You'll need to put the `#[serde(...)]` thing into a `cfg_attr` like `#[cfg_attr(feature = "foo", serde(with = "BigArray"))]`.

Also note that serde_big_array depends on serde itself so it would be better to put both serde and serde_big_array into the same optional feature.

**Comment by tpmccallum** [comment]
Ah, thank you so much @est31 
That worked a treat!

[The updated source code](https://github.com/tpmccallum/recrypt-rs/blob/optional_serde_feature/src/api_480.rs#L934) now builds sucessfully.

Here is a snippet ...
```
big_array! {
    BigArray;
    60,
}
#[derive(Clone, Copy)]
#[cfg_attr(
    feature = "serde",
    derive(Serialize, Deserialize),
    serde(crate = "serde_crate")
)]
struct SixtyBytes {
    #[cfg_attr(feature = "serde", serde(with = "BigArray"))]
    arr: [u8; Monty480::ENCODED_SIZE_BYTES],
}
```

Thanks again

**Comment by est31** [comment]
Glad to have been of help!
